name: Sync on DOM Cloud 
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: https://my.domcloud.co/api/githubdeploy
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.WEBHOOK_AUTH }}
          data: >-
            {"features":["node
            lts"],"nginx":{"root":"public_html/dist","locations":[{"match":"/","try_files":"$uri
            $uri/ /index.html"}]},"commands":["git pull origin main","npm
            install","npm run build","restart"]}
